### PR TITLE
Add hack to make it work with Auto Layout

### PR DESCRIPTION
**Pull request by gabmarfer**
Just added a couple of lines to make it compatible with Auto Layout. The finishing rect is calculated before loading the correct frame size of the Detail Controller, so it is necessary to layout its view with a little hack.

By the way, thanks for sharing your code!

### CODE REVIEW

**Comment by scalessec** [comment]
Hmm, I rather not have to do this hack. It's possible that the view just needs to be loaded first. Could you try this and let me know if it works?

``` objc
ZODetailViewController *detailController = (ZODetailViewController *)toViewController;
(void)[detailController view]; // force the view to load
return [detailController.imageView convertRect:detailController.imageView.bounds toView:relativeView];
```

If this works, I'll update the library to do this internally such that they'll be no changes/hacks required for anyone using this.

**Comment by gabmarfer** [comment]
I tried your suggestion, but it didn't work. 

My code to force the layout (calling setNeedsLayout and layoutIfNeeded) comes from this article: https://www.objc.io/issues/3-views/advanced-auto-layout-toolbox/

You are right and the library should do this internally, so I moved these two lines of code to `animateTransition:` method and it works fine.

**Comment by scalessec** [comment]
Great, thanks for fixing this. I'm going to merge and then update since this should only be an issue when presenting.

**Comment by scalessec** [comment]
Go ahead and pull `master` and let me know if all looks good for you.

**Comment by gabmarfer** [comment]
It works perfectly. Thanks!

**Pull request merged**
